name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x 
    - name: Install dependencies
      run: dotnet restore
      working-directory: pipeline testing
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: pipeline testing
    - name: Test
      run: dotnet test 
      working-directory: pipeline testing
